name: Build Workflow

on:
  workflow_call:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          set-safe-directory: '*'

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Build
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm run build