name: Pull Request CI

on:
  pull_request:
    branches:
      - develop

jobs:
  # Job 1: Linting
  lint:
    name: Run Linting
    uses: ./.github/workflows/lint.yml
    with:
        node-version: '18.x'

  # Job 2: Unit Tests
  unit-test:
    name: Run Unit Tests
    needs: lint
    uses: ./.github/workflows/unit-test.yml
    with:
        node-version: '18.x'

  # Job 3: SonarCloud Scan
  sonar-scan:
    name: Run SonarCloud Scan
    needs: unit-test
    uses: ./.github/workflows/sonar-scan.yml
    with:
      node-version: '18.x'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # Job 4: Build
  build:
    name: Build Workflow
    needs: sonar-scan
    uses: ./.github/workflows/build.yml

  # Job 5: Push Docker Image
  deployment:
    name: Push Docker Image to GCR
    needs: build # Build must pass first
    uses: ./.github/workflows/cd.yml
    secrets: inherit
