name: Pull Request CI

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  # Job 1: Linting
  lint:
    name: Run Linting
    uses: ./.github/workflows/lint.yml
    with:
        node-version: '18.x'

  # Job 2: Unit Tests
  unit-test:
    name: Run Unit Tests
    needs: lint # Linting must pass first
    uses: ./.github/workflows/unit-test.yml
    with:
        node-version: '18.x'

  # Job 3: SonarCloud Scan
  sonar-scan:
    name: Run SonarCloud Scan
    needs: unit-test # Tests must pass first
    uses: ./.github/workflows/sonar-scan.yml
    with:
      node-version: '18.x'
